### ISSUE TITLE
Do you have any another example?

### ISSUE THREAD

**Issue by moebiussurfing** [theKlanc/YAIC#1]
Hello @theKlanc , thanks for sharing!

I am trying to figure out how to use it...

I don't know how to "redirect" or to get notified on `customCommand1` function:
It's not being called  (when a new line is entered). 
Even when instantiated the object as : 
`myCustomConsole c = { true };`

```.cpp
	void customCommand1(std::stringstream args, customType data) {
		cout << "customCommand1" << endl;
	}
```

--

BTW, I also edited 'processCommand' to fill the upper text, but I am not sure if I am doing it well...

```.cpp
	void processCommand(T data) {
		cout << "processCommand(T data)" << endl;

		std::string command(_textEntryBuffer.data());
		std::fill(_textEntryBuffer.begin(), _textEntryBuffer.end(), '\0');
		_commandHistory.emplace_back(command);
		while (_commandHistory.size() > _maxHistoryLines) {
			_commandHistory.pop_front();
		}
		std::cout << command << std::endl;
		auto cmdName = command.substr(0, command.find(' '));
		auto cmd = _commandList.find(cmdName);
		if (cmd != _commandList.end()) {
			cmd->second(std::stringstream(command.substr(command.find(' ') + 1, command.size() - command.find(' ') - 1)), data);
		}



		//TODO:?
		_terminalBuffer += (string)(command);
		_terminalBuffer += "\n";
	};
```

Thanks

**Comment by theKlanc** [comment]
Hi @moebiussurfing ! Thanks for trying the library! :D
Could you show me your myCustomConsole definition? 
You just need to overload the constructor and call BIND(customCommand1) in its body, like in the example.
Here's an example of its usage in my own project: https://gitea.ledgedash.com/klanc/Spaceworks/src/branch/master/source/gameConsole.cpp

**Comment by moebiussurfing** [comment]
Thanks for your code. 
That helped. I understood a bit more. 

I learn to use the data as pointer, to allow modifying backwards.
`customType* data`

I also some of your argument's catcher/filter snippets.

--

PS

Here's my code:
https://github.com/moebiussurfing/ofxSurfingImGui/blob/e3f2c9ae4912993a8488d28ae73a563bc6ffa21a/src/ImGui/console/surfingConsole.h

What I don't understand is that when instantiating as `redir = true`,
`myCustomConsole c = { true };`
all the console app is handled on the imgui window..
but if `redir = false`, all the console goes through the Windows window.

I should check better. 
Thanks!

**Comment by theKlanc** [comment]
Glad it worked!
About the redirection, if you take a look at console's constructor you'll see that we steal stdout's rdbuf if redir is set to true:
```
console(bool redir = false) {
	if (redir) {
		_oldStdout = std::cout.rdbuf();
		std::cout.rdbuf(_stdout.rdbuf());
	}
	...
```
and we read from it inside show()

I'll leave the issue open in case you have further questions, :D
